### ISSUE TITLE
Unused fields in `DomainLookupTree` and `Node`.

### ISSUE THREAD

**Issue by ibnz36** [Phineas/domain-lookup-tree#1]
`DomainLookupTree` has a field named `minimum_level` and `Node` has a field named `data`.
None of this fields are used anywhere. And they are private fields.

What are they for?

**Comment by Phineas** [comment]
`minimum_level` is something I was going to implement later on which let you set a minimum domain level for lookups, so insertions would always be clustered and inserted by their minimum level which minimizes the traversal iterations if you always look up by at least a minimum level of domain. E.g. if minimum level was `1`, then inserting `www.google.com` would insert `google.com` into the root of the tree, and so on. Will likely implement it soon.

`data` is stored in each node for visibility & debugging purposes, or if someone's directly using the `traverse` function and wants to identify the node they've hit.
